version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
    time: "04:00"
  open-pull-requests-limit: 20
- package-ecosystem: npm
  directory: "/app"
  schedule:
    interval: daily
    time: "04:00"
  open-pull-requests-limit: 20
- package-ecosystem: npm
  directory: "/issh-core"
  schedule:
    interval: daily
    time: "04:00"
  open-pull-requests-limit: 20
- package-ecosystem: npm
  directory: "/issh-settings"
  schedule:
    interval: daily
    time: "04:00"
  open-pull-requests-limit: 20
- package-ecosystem: npm
  directory: "/issh-terminal"
  schedule:
    interval: daily
    time: "04:00"
  open-pull-requests-limit: 20
- package-ecosystem: npm
  directory: "/issh-local"
  schedule:
    interval: daily
    time: "04:00"
  open-pull-requests-limit: 20
- package-ecosystem: npm
  directory: "/issh-community-color-schemes"
  schedule:
    interval: daily
    time: "04:00"
  open-pull-requests-limit: 20
- package-ecosystem: npm
  directory: "/issh-electron"
  schedule:
    interval: daily
    time: "04:00"
  open-pull-requests-limit: 20
- package-ecosystem: npm
  directory: "/issh-ssh"
  schedule:
    interval: daily
    time: "04:00"
  open-pull-requests-limit: 20
- package-ecosystem: github-actions
  directory: "/"
  schedule:
    interval: daily
    time: "04:00"
  open-pull-requests-limit: 20
