---
name: "tagged-release"

on:
  push:
    tags:
      - "v*"

permissions:
  contents: write

jobs:
  tagged-release:
    name: "Tagged Release"
    runs-on: "ubuntu-latest"

    steps:
      - name: Create draft release
        env:
          GH_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
        run: >-
          gh release create "${GITHUB_REF_NAME}"
          --draft
          --generate-notes
          --verify-tag
          --title "${GITHUB_REF_NAME}"
